spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_management_system?useSSL=false
    username: postgres
    password: dbpass
    driverClassName: org.postgresql.Driver
    
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format-sql: true
      
  application:
    name: SERVICE-CUSTOMER

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      

server:
  port:
    9002
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
    
  